// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/dictionary/proto/dictionary.proto

package dictionary

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Keyword  *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
	Name     *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *ListDictionaryRequest) Reset() {
	*x = ListDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryRequest) ProtoMessage() {}

func (x *ListDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryRequest.ProtoReflect.Descriptor instead.
func (*ListDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *ListDictionaryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDictionaryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictionaryRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ListDictionaryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListDictionaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListDictionaryReply_Dictionary `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListDictionaryReply) Reset() {
	*x = ListDictionaryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryReply) ProtoMessage() {}

func (x *ListDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryReply.ProtoReflect.Descriptor instead.
func (*ListDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *ListDictionaryReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictionaryReply) GetList() []*ListDictionaryReply_Dictionary {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword     string  `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type        string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *CreateDictionaryRequest) Reset() {
	*x = CreateDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryRequest) ProtoMessage() {}

func (x *CreateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDictionaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateDictionaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDictionaryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDictionaryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateDictionaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDictionaryReply) Reset() {
	*x = CreateDictionaryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryReply) ProtoMessage() {}

func (x *CreateDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryReply.ProtoReflect.Descriptor instead.
func (*CreateDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDictionaryReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword     string  `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type        string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *UpdateDictionaryRequest) Reset() {
	*x = UpdateDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryRequest) ProtoMessage() {}

func (x *UpdateDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDictionaryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *UpdateDictionaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDictionaryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateDictionaryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateDictionaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDictionaryReply) Reset() {
	*x = UpdateDictionaryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryReply) ProtoMessage() {}

func (x *UpdateDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{5}
}

type DeleteDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDictionaryRequest) Reset() {
	*x = DeleteDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryRequest) ProtoMessage() {}

func (x *DeleteDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDictionaryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDictionaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDictionaryReply) Reset() {
	*x = DeleteDictionaryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryReply) ProtoMessage() {}

func (x *DeleteDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryReply.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{7}
}

type GetDictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *uint32 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Keyword *string `protobuf:"bytes,2,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`
}

func (x *GetDictionaryRequest) Reset() {
	*x = GetDictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryRequest) ProtoMessage() {}

func (x *GetDictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryRequest.ProtoReflect.Descriptor instead.
func (*GetDictionaryRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{8}
}

func (x *GetDictionaryRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetDictionaryRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type GetDictionaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword     string  `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type        string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt   uint32  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   uint32  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *GetDictionaryReply) Reset() {
	*x = GetDictionaryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryReply) ProtoMessage() {}

func (x *GetDictionaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryReply.ProtoReflect.Descriptor instead.
func (*GetDictionaryReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{9}
}

func (x *GetDictionaryReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDictionaryReply) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetDictionaryReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDictionaryReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDictionaryReply) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GetDictionaryReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetDictionaryReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetDictionaryValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *GetDictionaryValuesRequest) Reset() {
	*x = GetDictionaryValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesRequest) ProtoMessage() {}

func (x *GetDictionaryValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesRequest.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{10}
}

func (x *GetDictionaryValuesRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type GetDictionaryValuesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dict map[string]*GetDictionaryValuesReply_Value `protobuf:"bytes,1,rep,name=dict,proto3" json:"dict,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetDictionaryValuesReply) Reset() {
	*x = GetDictionaryValuesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply) ProtoMessage() {}

func (x *GetDictionaryValuesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{11}
}

func (x *GetDictionaryValuesReply) GetDict() map[string]*GetDictionaryValuesReply_Value {
	if x != nil {
		return x.Dict
	}
	return nil
}

type ListDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	DictionaryId uint32  `protobuf:"varint,3,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        *string `protobuf:"bytes,4,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Value        *string `protobuf:"bytes,5,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Status       *bool   `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ListDictionaryValueRequest) Reset() {
	*x = ListDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueRequest) ProtoMessage() {}

func (x *ListDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{12}
}

func (x *ListDictionaryValueRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type ListDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListDictionaryValueReply_DictionaryValue `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListDictionaryValueReply) Reset() {
	*x = ListDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueReply) ProtoMessage() {}

func (x *ListDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{13}
}

func (x *ListDictionaryValueReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictionaryValueReply) GetList() []*ListDictionaryValueReply_DictionaryValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DictionaryId uint32  `protobuf:"varint,1,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value        string  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ParentId     uint32  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Status       *bool   `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Weight       *int32  `protobuf:"varint,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string `protobuf:"bytes,7,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string `protobuf:"bytes,8,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *CreateDictionaryValueRequest) Reset() {
	*x = CreateDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryValueRequest) ProtoMessage() {}

func (x *CreateDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *CreateDictionaryValueRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateDictionaryValueRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *CreateDictionaryValueRequest) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *CreateDictionaryValueRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDictionaryValueReply) Reset() {
	*x = CreateDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryValueReply) ProtoMessage() {}

func (x *CreateDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*CreateDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{15}
}

func (x *CreateDictionaryValueReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DictionaryId uint32  `protobuf:"varint,2,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        string  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Value        string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ParentId     uint32  `protobuf:"varint,5,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Weight       *int32  `protobuf:"varint,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string `protobuf:"bytes,7,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string `protobuf:"bytes,8,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *UpdateDictionaryValueRequest) Reset() {
	*x = UpdateDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueRequest) ProtoMessage() {}

func (x *UpdateDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDictionaryValueRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDictionaryValueReply) Reset() {
	*x = UpdateDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueReply) ProtoMessage() {}

func (x *UpdateDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{17}
}

type UpdateDictionaryValueStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateDictionaryValueStatusRequest) Reset() {
	*x = UpdateDictionaryValueStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueStatusRequest) ProtoMessage() {}

func (x *UpdateDictionaryValueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateDictionaryValueStatusRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryValueStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateDictionaryValueStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDictionaryValueStatusReply) Reset() {
	*x = UpdateDictionaryValueStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueStatusReply) ProtoMessage() {}

func (x *UpdateDictionaryValueStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueStatusReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{19}
}

type DeleteDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDictionaryValueRequest) Reset() {
	*x = DeleteDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryValueRequest) ProtoMessage() {}

func (x *DeleteDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteDictionaryValueRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDictionaryValueReply) Reset() {
	*x = DeleteDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryValueReply) ProtoMessage() {}

func (x *DeleteDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{21}
}

type ListDictionaryReply_Dictionary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword     string  `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type        string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt   uint32  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   uint32  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *ListDictionaryReply_Dictionary) Reset() {
	*x = ListDictionaryReply_Dictionary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryReply_Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryReply_Dictionary) ProtoMessage() {}

func (x *ListDictionaryReply_Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryReply_Dictionary.ProtoReflect.Descriptor instead.
func (*ListDictionaryReply_Dictionary) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListDictionaryReply_Dictionary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListDictionaryReply_Dictionary) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListDictionaryReply_Dictionary) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListDictionaryReply_Dictionary) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetDictionaryValuesReply_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetDictionaryValuesReply_Value_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetDictionaryValuesReply_Value) Reset() {
	*x = GetDictionaryValuesReply_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply_Value) ProtoMessage() {}

func (x *GetDictionaryValuesReply_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply_Value.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply_Value) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetDictionaryValuesReply_Value) GetList() []*GetDictionaryValuesReply_Value_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type GetDictionaryValuesReply_Value_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label       string                                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value       string                                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type        *string                                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra       *string                                `protobuf:"bytes,4,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description *string                                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Children    []*GetDictionaryValuesReply_Value_Item `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *GetDictionaryValuesReply_Value_Item) Reset() {
	*x = GetDictionaryValuesReply_Value_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply_Value_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply_Value_Item) ProtoMessage() {}

func (x *GetDictionaryValuesReply_Value_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply_Value_Item.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply_Value_Item) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{11, 0, 0}
}

func (x *GetDictionaryValuesReply_Value_Item) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetChildren() []*GetDictionaryValuesReply_Value_Item {
	if x != nil {
		return x.Children
	}
	return nil
}

type ListDictionaryValueReply_DictionaryValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DictionaryId uint32                                      `protobuf:"varint,2,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	ParentId     uint32                                      `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Label        string                                      `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Value        string                                      `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Status       *bool                                       `protobuf:"varint,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Weight       *int32                                      `protobuf:"varint,7,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string                                     `protobuf:"bytes,8,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string                                     `protobuf:"bytes,9,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string                                     `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt    uint32                                      `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    uint32                                      `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Children     []*ListDictionaryValueReply_DictionaryValue `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *ListDictionaryValueReply_DictionaryValue) Reset() {
	*x = ListDictionaryValueReply_DictionaryValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueReply_DictionaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueReply_DictionaryValue) ProtoMessage() {}

func (x *ListDictionaryValueReply_DictionaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_dictionary_proto_dictionary_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueReply_DictionaryValue.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueReply_DictionaryValue) Descriptor() ([]byte, []int) {
	return file_api_dictionary_proto_dictionary_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ListDictionaryValueReply_DictionaryValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *ListDictionaryValueReply_DictionaryValue) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetChildren() []*ListDictionaryValueReply_DictionaryValue {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_api_dictionary_proto_dictionary_proto protoreflect.FileDescriptor

var file_api_dictionary_proto_dictionary_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xcb, 0x02, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x4a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x36, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xd1, 0x01,
	0x0a, 0x0a, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xad, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xab, 0x01, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x32, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28,
	0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x6f,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x48, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x48, 0x01,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0xd9, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07,
	0x92, 0x01, 0x04, 0x08, 0x01, 0x18, 0x01, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0xc2, 0x04, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e,
	0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44,
	0x69, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x69, 0x63, 0x74, 0x1a, 0xe4,
	0x02, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x89, 0x02, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88,
	0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x57, 0x0a, 0x08, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x6f, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x4c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf6, 0x01, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xfe, 0x04, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x54, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x40, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xf5, 0x03, 0x0a, 0x0f, 0x44, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x5c, 0x0a, 0x08, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xf3, 0x02, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01,
	0x52, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xe4, 0x02, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b,
	0x0a, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x0c, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x55, 0x0a, 0x22, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x22, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x37, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a,
	0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3d, 0x0a, 0x16, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x01, 0x5a, 0x21, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x3b,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_dictionary_proto_dictionary_proto_rawDescOnce sync.Once
	file_api_dictionary_proto_dictionary_proto_rawDescData = file_api_dictionary_proto_dictionary_proto_rawDesc
)

func file_api_dictionary_proto_dictionary_proto_rawDescGZIP() []byte {
	file_api_dictionary_proto_dictionary_proto_rawDescOnce.Do(func() {
		file_api_dictionary_proto_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dictionary_proto_dictionary_proto_rawDescData)
	})
	return file_api_dictionary_proto_dictionary_proto_rawDescData
}

var (
	file_api_dictionary_proto_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
	file_api_dictionary_proto_dictionary_proto_goTypes  = []interface{}{
		(*ListDictionaryRequest)(nil),                    // 0: manager.api.dictionary.ListDictionaryRequest
		(*ListDictionaryReply)(nil),                      // 1: manager.api.dictionary.ListDictionaryReply
		(*CreateDictionaryRequest)(nil),                  // 2: manager.api.dictionary.CreateDictionaryRequest
		(*CreateDictionaryReply)(nil),                    // 3: manager.api.dictionary.CreateDictionaryReply
		(*UpdateDictionaryRequest)(nil),                  // 4: manager.api.dictionary.UpdateDictionaryRequest
		(*UpdateDictionaryReply)(nil),                    // 5: manager.api.dictionary.UpdateDictionaryReply
		(*DeleteDictionaryRequest)(nil),                  // 6: manager.api.dictionary.DeleteDictionaryRequest
		(*DeleteDictionaryReply)(nil),                    // 7: manager.api.dictionary.DeleteDictionaryReply
		(*GetDictionaryRequest)(nil),                     // 8: manager.api.dictionary.GetDictionaryRequest
		(*GetDictionaryReply)(nil),                       // 9: manager.api.dictionary.GetDictionaryReply
		(*GetDictionaryValuesRequest)(nil),               // 10: manager.api.dictionary.GetDictionaryValuesRequest
		(*GetDictionaryValuesReply)(nil),                 // 11: manager.api.dictionary.GetDictionaryValuesReply
		(*ListDictionaryValueRequest)(nil),               // 12: manager.api.dictionary.ListDictionaryValueRequest
		(*ListDictionaryValueReply)(nil),                 // 13: manager.api.dictionary.ListDictionaryValueReply
		(*CreateDictionaryValueRequest)(nil),             // 14: manager.api.dictionary.CreateDictionaryValueRequest
		(*CreateDictionaryValueReply)(nil),               // 15: manager.api.dictionary.CreateDictionaryValueReply
		(*UpdateDictionaryValueRequest)(nil),             // 16: manager.api.dictionary.UpdateDictionaryValueRequest
		(*UpdateDictionaryValueReply)(nil),               // 17: manager.api.dictionary.UpdateDictionaryValueReply
		(*UpdateDictionaryValueStatusRequest)(nil),       // 18: manager.api.dictionary.UpdateDictionaryValueStatusRequest
		(*UpdateDictionaryValueStatusReply)(nil),         // 19: manager.api.dictionary.UpdateDictionaryValueStatusReply
		(*DeleteDictionaryValueRequest)(nil),             // 20: manager.api.dictionary.DeleteDictionaryValueRequest
		(*DeleteDictionaryValueReply)(nil),               // 21: manager.api.dictionary.DeleteDictionaryValueReply
		(*ListDictionaryReply_Dictionary)(nil),           // 22: manager.api.dictionary.ListDictionaryReply.Dictionary
		(*GetDictionaryValuesReply_Value)(nil),           // 23: manager.api.dictionary.GetDictionaryValuesReply.Value
		nil,                                              // 24: manager.api.dictionary.GetDictionaryValuesReply.DictEntry
		(*GetDictionaryValuesReply_Value_Item)(nil),      // 25: manager.api.dictionary.GetDictionaryValuesReply.Value.Item
		(*ListDictionaryValueReply_DictionaryValue)(nil), // 26: manager.api.dictionary.ListDictionaryValueReply.DictionaryValue
	}
)

var file_api_dictionary_proto_dictionary_proto_depIdxs = []int32{
	22, // 0: manager.api.dictionary.ListDictionaryReply.list:type_name -> manager.api.dictionary.ListDictionaryReply.Dictionary
	24, // 1: manager.api.dictionary.GetDictionaryValuesReply.dict:type_name -> manager.api.dictionary.GetDictionaryValuesReply.DictEntry
	26, // 2: manager.api.dictionary.ListDictionaryValueReply.list:type_name -> manager.api.dictionary.ListDictionaryValueReply.DictionaryValue
	25, // 3: manager.api.dictionary.GetDictionaryValuesReply.Value.list:type_name -> manager.api.dictionary.GetDictionaryValuesReply.Value.Item
	23, // 4: manager.api.dictionary.GetDictionaryValuesReply.DictEntry.value:type_name -> manager.api.dictionary.GetDictionaryValuesReply.Value
	25, // 5: manager.api.dictionary.GetDictionaryValuesReply.Value.Item.children:type_name -> manager.api.dictionary.GetDictionaryValuesReply.Value.Item
	26, // 6: manager.api.dictionary.ListDictionaryValueReply.DictionaryValue.children:type_name -> manager.api.dictionary.ListDictionaryValueReply.DictionaryValue
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_dictionary_proto_dictionary_proto_init() }
func file_api_dictionary_proto_dictionary_proto_init() {
	if File_api_dictionary_proto_dictionary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dictionary_proto_dictionary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryReply_Dictionary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply_Value_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dictionary_proto_dictionary_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueReply_DictionaryValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_dictionary_proto_dictionary_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[22].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[25].OneofWrappers = []interface{}{}
	file_api_dictionary_proto_dictionary_proto_msgTypes[26].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dictionary_proto_dictionary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_dictionary_proto_dictionary_proto_goTypes,
		DependencyIndexes: file_api_dictionary_proto_dictionary_proto_depIdxs,
		MessageInfos:      file_api_dictionary_proto_dictionary_proto_msgTypes,
	}.Build()
	File_api_dictionary_proto_dictionary_proto = out.File
	file_api_dictionary_proto_dictionary_proto_rawDesc = nil
	file_api_dictionary_proto_dictionary_proto_goTypes = nil
	file_api_dictionary_proto_dictionary_proto_depIdxs = nil
}
