// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/tenantapp/proto/tenantapp.proto

package tenantapp

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantAppSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableNotice *bool   `protobuf:"varint,1,opt,name=enableNotice,proto3,oneof" json:"enableNotice,omitempty"`
	NoticeEmail  *string `protobuf:"bytes,2,opt,name=noticeEmail,proto3,oneof" json:"noticeEmail,omitempty"`
}

func (x *TenantAppSetting) Reset() {
	*x = TenantAppSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantAppSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAppSetting) ProtoMessage() {}

func (x *TenantAppSetting) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantAppSetting.ProtoReflect.Descriptor instead.
func (*TenantAppSetting) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{0}
}

func (x *TenantAppSetting) GetEnableNotice() bool {
	if x != nil && x.EnableNotice != nil {
		return *x.EnableNotice
	}
	return false
}

func (x *TenantAppSetting) GetNoticeEmail() string {
	if x != nil && x.NoticeEmail != nil {
		return *x.NoticeEmail
	}
	return ""
}

type CreateTenantAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId  uint32            `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	AppId     uint32            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	ExpiredAt uint32            `protobuf:"varint,3,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	MenuIds   []uint32          `protobuf:"varint,4,rep,packed,name=menuIds,proto3" json:"menuIds,omitempty"`
	Setting   *TenantAppSetting `protobuf:"bytes,5,opt,name=setting,proto3" json:"setting,omitempty"`
}

func (x *CreateTenantAppRequest) Reset() {
	*x = CreateTenantAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAppRequest) ProtoMessage() {}

func (x *CreateTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAppRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantAppRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateTenantAppRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CreateTenantAppRequest) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *CreateTenantAppRequest) GetMenuIds() []uint32 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *CreateTenantAppRequest) GetSetting() *TenantAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type CreateTenantAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTenantAppReply) Reset() {
	*x = CreateTenantAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTenantAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAppReply) ProtoMessage() {}

func (x *CreateTenantAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAppReply.ProtoReflect.Descriptor instead.
func (*CreateTenantAppReply) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantAppReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTenantAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId  uint32            `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	AppId     uint32            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	ExpiredAt uint32            `protobuf:"varint,3,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	MenuIds   []uint32          `protobuf:"varint,4,rep,packed,name=menuIds,proto3" json:"menuIds,omitempty"`
	Setting   *TenantAppSetting `protobuf:"bytes,5,opt,name=setting,proto3,oneof" json:"setting,omitempty"`
}

func (x *UpdateTenantAppRequest) Reset() {
	*x = UpdateTenantAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantAppRequest) ProtoMessage() {}

func (x *UpdateTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTenantAppRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateTenantAppRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *UpdateTenantAppRequest) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *UpdateTenantAppRequest) GetMenuIds() []uint32 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *UpdateTenantAppRequest) GetSetting() *TenantAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type UpdateTenantAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTenantAppReply) Reset() {
	*x = UpdateTenantAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTenantAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantAppReply) ProtoMessage() {}

func (x *UpdateTenantAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantAppReply.ProtoReflect.Descriptor instead.
func (*UpdateTenantAppReply) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{4}
}

type DeleteTenantAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId uint32 `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	AppId    uint32 `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
}

func (x *DeleteTenantAppRequest) Reset() {
	*x = DeleteTenantAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantAppRequest) ProtoMessage() {}

func (x *DeleteTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTenantAppRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeleteTenantAppRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type DeleteTenantAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTenantAppReply) Reset() {
	*x = DeleteTenantAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTenantAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantAppReply) ProtoMessage() {}

func (x *DeleteTenantAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantAppReply.ProtoReflect.Descriptor instead.
func (*DeleteTenantAppReply) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{6}
}

type ListTenantAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Order      *string `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
	OrderBy    *string `protobuf:"bytes,4,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	AppName    *string `protobuf:"bytes,5,opt,name=appName,proto3,oneof" json:"appName,omitempty"`
	AppKeyword *string `protobuf:"bytes,6,opt,name=appKeyword,proto3,oneof" json:"appKeyword,omitempty"`
	TenantId   uint32  `protobuf:"varint,7,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
}

func (x *ListTenantAppRequest) Reset() {
	*x = ListTenantAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantAppRequest) ProtoMessage() {}

func (x *ListTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantAppRequest.ProtoReflect.Descriptor instead.
func (*ListTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{7}
}

func (x *ListTenantAppRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTenantAppRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantAppRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListTenantAppRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListTenantAppRequest) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *ListTenantAppRequest) GetAppKeyword() string {
	if x != nil && x.AppKeyword != nil {
		return *x.AppKeyword
	}
	return ""
}

func (x *ListTenantAppRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Logo    string `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name    string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{8}
}

func (x *App) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *App) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *App) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTenantAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*ListTenantAppReply_Data `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total uint32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListTenantAppReply) Reset() {
	*x = ListTenantAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTenantAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantAppReply) ProtoMessage() {}

func (x *ListTenantAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantAppReply.ProtoReflect.Descriptor instead.
func (*ListTenantAppReply) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{9}
}

func (x *ListTenantAppReply) GetList() []*ListTenantAppReply_Data {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTenantAppReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTenantAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId uint32 `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	AppId    uint32 `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
}

func (x *GetTenantAppRequest) Reset() {
	*x = GetTenantAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantAppRequest) ProtoMessage() {}

func (x *GetTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantAppRequest.ProtoReflect.Descriptor instead.
func (*GetTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{10}
}

func (x *GetTenantAppRequest) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetTenantAppRequest) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type GetTenantAppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId     uint32            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	TenantId  uint32            `protobuf:"varint,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	ExpiredAt uint32            `protobuf:"varint,4,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	CreatedAt uint32            `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32            `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	App       *App              `protobuf:"bytes,7,opt,name=app,proto3" json:"app,omitempty"`
	MenuIds   []uint32          `protobuf:"varint,8,rep,packed,name=menuIds,proto3" json:"menuIds,omitempty"`
	Setting   *TenantAppSetting `protobuf:"bytes,9,opt,name=setting,proto3" json:"setting,omitempty"`
}

func (x *GetTenantAppReply) Reset() {
	*x = GetTenantAppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTenantAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantAppReply) ProtoMessage() {}

func (x *GetTenantAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantAppReply.ProtoReflect.Descriptor instead.
func (*GetTenantAppReply) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{11}
}

func (x *GetTenantAppReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTenantAppReply) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetTenantAppReply) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetTenantAppReply) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *GetTenantAppReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTenantAppReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetTenantAppReply) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetTenantAppReply) GetMenuIds() []uint32 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *GetTenantAppReply) GetSetting() *TenantAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type ListTenantAppReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId     uint32            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	TenantId  uint32            `protobuf:"varint,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	ExpiredAt uint32            `protobuf:"varint,4,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	CreatedAt uint32            `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32            `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	App       *App              `protobuf:"bytes,7,opt,name=app,proto3" json:"app,omitempty"`
	MenuIds   []uint32          `protobuf:"varint,8,rep,packed,name=menuIds,proto3" json:"menuIds,omitempty"`
	Setting   *TenantAppSetting `protobuf:"bytes,9,opt,name=setting,proto3" json:"setting,omitempty"`
}

func (x *ListTenantAppReply_Data) Reset() {
	*x = ListTenantAppReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTenantAppReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantAppReply_Data) ProtoMessage() {}

func (x *ListTenantAppReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenantapp_proto_tenantapp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantAppReply_Data.ProtoReflect.Descriptor instead.
func (*ListTenantAppReply_Data) Descriptor() ([]byte, []int) {
	return file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListTenantAppReply_Data) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListTenantAppReply_Data) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ListTenantAppReply_Data) GetMenuIds() []uint32 {
	if x != nil {
		return x.MenuIds
	}
	return nil
}

func (x *ListTenantAppReply_Data) GetSetting() *TenantAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

var File_api_tenantapp_proto_tenantapp_proto protoreflect.FileDescriptor

var file_api_tenantapp_proto_tenantapp_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x41, 0x70, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x0c, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x0c, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x60,
	0x01, 0x48, 0x01, 0x52, 0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0xea, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52,
	0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65,
	0x6e, 0x75, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x08, 0xfa, 0x42, 0x05,
	0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x73, 0x12, 0x41,
	0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70,
	0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfb, 0x01, 0x0a, 0x16, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52,
	0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28,
	0x01, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x22, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x64, 0x73, 0x12, 0x46, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x54, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x5c, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xae, 0x02, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa,
	0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07,
	0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x61,
	0x70, 0x70, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x03, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x23, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x08, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61, 0x70, 0x70, 0x4b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x57, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x9e, 0x03, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x1a, 0xad, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x03,
	0x61, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x73, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x73, 0x12, 0x41, 0x0a,
	0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x59, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02,
	0x28, 0x01, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0xba, 0x02, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2c, 0x0a,
	0x03, 0x61, 0x70, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61,
	0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x6e, 0x75, 0x49, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x65,
	0x6e, 0x75, 0x49, 0x64, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x54,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x40, 0x0a, 0x1b, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70,
	0x3b, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_tenantapp_proto_tenantapp_proto_rawDescOnce sync.Once
	file_api_tenantapp_proto_tenantapp_proto_rawDescData = file_api_tenantapp_proto_tenantapp_proto_rawDesc
)

func file_api_tenantapp_proto_tenantapp_proto_rawDescGZIP() []byte {
	file_api_tenantapp_proto_tenantapp_proto_rawDescOnce.Do(func() {
		file_api_tenantapp_proto_tenantapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_tenantapp_proto_tenantapp_proto_rawDescData)
	})
	return file_api_tenantapp_proto_tenantapp_proto_rawDescData
}

var (
	file_api_tenantapp_proto_tenantapp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
	file_api_tenantapp_proto_tenantapp_proto_goTypes  = []interface{}{
		(*TenantAppSetting)(nil),        // 0: manager.api.tenantapp.TenantAppSetting
		(*CreateTenantAppRequest)(nil),  // 1: manager.api.tenantapp.CreateTenantAppRequest
		(*CreateTenantAppReply)(nil),    // 2: manager.api.tenantapp.CreateTenantAppReply
		(*UpdateTenantAppRequest)(nil),  // 3: manager.api.tenantapp.UpdateTenantAppRequest
		(*UpdateTenantAppReply)(nil),    // 4: manager.api.tenantapp.UpdateTenantAppReply
		(*DeleteTenantAppRequest)(nil),  // 5: manager.api.tenantapp.DeleteTenantAppRequest
		(*DeleteTenantAppReply)(nil),    // 6: manager.api.tenantapp.DeleteTenantAppReply
		(*ListTenantAppRequest)(nil),    // 7: manager.api.tenantapp.ListTenantAppRequest
		(*App)(nil),                     // 8: manager.api.tenantapp.App
		(*ListTenantAppReply)(nil),      // 9: manager.api.tenantapp.ListTenantAppReply
		(*GetTenantAppRequest)(nil),     // 10: manager.api.tenantapp.GetTenantAppRequest
		(*GetTenantAppReply)(nil),       // 11: manager.api.tenantapp.GetTenantAppReply
		(*ListTenantAppReply_Data)(nil), // 12: manager.api.tenantapp.ListTenantAppReply.Data
	}
)

var file_api_tenantapp_proto_tenantapp_proto_depIdxs = []int32{
	0,  // 0: manager.api.tenantapp.CreateTenantAppRequest.setting:type_name -> manager.api.tenantapp.TenantAppSetting
	0,  // 1: manager.api.tenantapp.UpdateTenantAppRequest.setting:type_name -> manager.api.tenantapp.TenantAppSetting
	12, // 2: manager.api.tenantapp.ListTenantAppReply.list:type_name -> manager.api.tenantapp.ListTenantAppReply.Data
	8,  // 3: manager.api.tenantapp.GetTenantAppReply.app:type_name -> manager.api.tenantapp.App
	0,  // 4: manager.api.tenantapp.GetTenantAppReply.setting:type_name -> manager.api.tenantapp.TenantAppSetting
	8,  // 5: manager.api.tenantapp.ListTenantAppReply.Data.app:type_name -> manager.api.tenantapp.App
	0,  // 6: manager.api.tenantapp.ListTenantAppReply.Data.setting:type_name -> manager.api.tenantapp.TenantAppSetting
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_tenantapp_proto_tenantapp_proto_init() }
func file_api_tenantapp_proto_tenantapp_proto_init() {
	if File_api_tenantapp_proto_tenantapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantAppSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTenantAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTenantAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTenantAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTenantAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTenantAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTenantAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTenantAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTenantAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTenantAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTenantAppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tenantapp_proto_tenantapp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTenantAppReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_tenantapp_proto_tenantapp_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_tenantapp_proto_tenantapp_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_api_tenantapp_proto_tenantapp_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_tenantapp_proto_tenantapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_tenantapp_proto_tenantapp_proto_goTypes,
		DependencyIndexes: file_api_tenantapp_proto_tenantapp_proto_depIdxs,
		MessageInfos:      file_api_tenantapp_proto_tenantapp_proto_msgTypes,
	}.Build()
	File_api_tenantapp_proto_tenantapp_proto = out.File
	file_api_tenantapp_proto_tenantapp_proto_rawDesc = nil
	file_api_tenantapp_proto_tenantapp_proto_goTypes = nil
	file_api_tenantapp_proto_tenantapp_proto_depIdxs = nil
}
