package menu

import (
	"google.golang.org/protobuf/proto"

	"github.com/limes-cloud/manager/consts"
	"github.com/limes-cloud/manager/internal/model"
)

var menus = []*model.Menu{
	{
		App:        "SystemPlatform",
		Title:      "管理平台",
		Type:       consts.MenuRoot,
		Keyword:    proto.String("SystemPlatform"),
		Icon:       proto.String("apps"),
		Api:        nil,
		Method:     nil,
		Path:       proto.String("/"),
		Permission: nil,
		Component:  proto.String("Layout"),
		Redirect:   nil,
		Weight:     proto.Uint32(2),
		IsHidden:   proto.Bool(false),
		IsCache:    nil,
		IsHome:     nil,
		IsAffix:    nil,
		Children: []*model.Menu{
			{
				App:        "SystemPlatform",
				Title:      "首页面板",
				Type:       consts.MenuPage,
				Keyword:    proto.String("Dashboard"),
				Icon:       proto.String("dashboard"),
				Api:        nil,
				Method:     nil,
				Path:       proto.String("/dashboard"),
				Permission: nil,
				Component:  proto.String("dashboard/index"),
				Redirect:   nil,
				Weight:     proto.Uint32(0),
				IsHidden:   proto.Bool(false),
				IsCache:    proto.Bool(true),
				IsHome:     proto.Bool(true),
				IsAffix:    proto.Bool(true),
				Children:   nil,
			},
			{
				App:        "SystemPlatform",
				Title:      "管理中心",
				Type:       consts.MenuPage,
				Keyword:    proto.String("SystemPlatformManager"),
				Icon:       proto.String("apps"),
				Api:        nil,
				Method:     nil,
				Path:       proto.String("/manager"),
				Permission: nil,
				Component:  nil,
				Redirect:   nil,
				Weight:     proto.Uint32(0),
				IsHidden:   proto.Bool(false),
				IsCache:    nil,
				IsHome:     nil,
				IsAffix:    nil,
				Children: []*model.Menu{
					{
						App:        "SystemPlatform",
						Title:      "基础接口",
						Type:       consts.MenuGroup,
						Keyword:    proto.String("BaseApi"),
						Icon:       proto.String("apps"),
						Api:        nil,
						Method:     nil,
						Path:       nil,
						Permission: nil,
						Component:  nil,
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   proto.Bool(true),
						IsCache:    nil,
						IsHome:     nil,
						IsAffix:    nil,
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "获取用户部门",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/department/tree"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "获取个人用户信息",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user/current"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "获取用户可见角色树",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role/tree"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "获取用户菜单",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role/menu/tree"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "退出登录",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/logout"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "刷新token",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/token/refresh"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "用户登录",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/login"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "获取登录验证码",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/login/captcha"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "获取系统基础设置",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/setting"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "接口鉴权",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/auth"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "切换用户角色",
								Type:       "BA",
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user/role/switch"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: nil,
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "字典管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("Dict"),
						Icon:       proto.String("storage"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/dict"),
						Permission: nil,
						Component:  proto.String("manager/dict/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查询字典",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dicts"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("manager:dict:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增字典",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:dict:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改字典",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:dict:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除字典",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:dict:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "字典值管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("DictValue"),
						Icon:       proto.String("storage"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/dict_value"),
						Permission: nil,
						Component:  proto.String("manager/dict/value/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   proto.Bool(true),
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "查询字典值",
							Type:       consts.MenuApi,
							Keyword:    nil,
							Icon:       nil,
							Api:        proto.String("/manager/v1/dict/values"),
							Method:     proto.String("GET"),
							Path:       nil,
							Permission: proto.String("manager:dict:value:query"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children:   nil,
						},
							{
								App:        "SystemPlatform",
								Title:      "新增字典值",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict/value"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:dict:value:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改字典值",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict/value"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:dict:value:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除字典值",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/dict/value"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:dict:value:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "菜单管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ManagerMenu"),
						Icon:       proto.String("menu"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/menu"),
						Permission: nil,
						Component:  proto.String("manager/menu/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   proto.Bool(false),
						IsCache:    proto.Bool(true),
						IsHome:     proto.Bool(true),
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查询菜单",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/menu/tree"),
								Method:     proto.String("GET"),
								Path:       proto.String(""),
								Permission: proto.String("manager:menu:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增菜单",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/menu"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:menu:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改菜单",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/menu"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:menu:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除菜单",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/menu"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:menu:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "职位管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("JobUser"),
						Icon:       proto.String("tag"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/job"),
						Permission: nil,
						Component:  proto.String("manager/job/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "查询职位",
							Type:       consts.MenuApi,
							Keyword:    nil,
							Icon:       nil,
							Api:        proto.String("/manager/v1/jobs"),
							Method:     proto.String("GET"),
							Path:       nil,
							Permission: proto.String("manager:job:query"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children:   nil,
						},
							{
								App:        "SystemPlatform",
								Title:      "新增职位",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/job"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:job:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改职位",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/job"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:job:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除职位",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/job"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:job:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "部门管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ManagerDepartment"),
						Icon:       proto.String("user-group"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/department"),
						Permission: nil,
						Component:  proto.String("manager/department/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   proto.Bool(false),
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "查看部门",
							Type:       consts.MenuApi,
							Keyword:    nil,
							Icon:       nil,
							Api:        proto.String("/manager/v1/department/tree"),
							Method:     proto.String("GET"),
							Path:       nil,
							Permission: proto.String("manager:department:query"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children:   nil,
						},
							{
								App:        "SystemPlatform",
								Title:      "新增部门",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/department"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:department:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改部门",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/department"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:department:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除部门",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/department"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:department:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "角色管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ManagerRole"),
						Icon:       proto.String("safe"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/role"),
						Permission: nil,
						Component:  proto.String("manager/role/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(false),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "查询角色",
							Type:       consts.MenuApi,
							Keyword:    nil,
							Icon:       nil,
							Api:        proto.String("/manager/v1/role/tree"),
							Method:     proto.String("GET"),
							Path:       nil,
							Permission: proto.String("manager:role:query"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children:   nil,
						},
							{
								App:        "SystemPlatform",
								Title:      "新增角色",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:role:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改角色",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:role:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除角色",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:role:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "角色菜单管理",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/role/menu/tree"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("manager:role:menu"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{{
									App:        "SystemPlatform",
									Title:      "查询角色菜单",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/manager/v1/role/menu/ids"),
									Method:     proto.String("GET"),
									Path:       nil,
									Permission: proto.String("manager:role:menu:query"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
									{
										App:        "SystemPlatform",
										Title:      "修改角色菜单",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/manager/v1/role/menu"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("manager:role:menu:update"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
								},
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "用户管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ManagerUser"),
						Icon:       proto.String("user"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/manager/user"),
						Permission: nil,
						Component:  proto.String("manager/user/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "查询用户",
							Type:       consts.MenuApi,
							Keyword:    nil,
							Icon:       nil,
							Api:        proto.String("/manager/v1/users"),
							Method:     proto.String("GET"),
							Path:       nil,
							Permission: proto.String("manager:user:query"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children:   nil,
						},
							{
								App:        "SystemPlatform",
								Title:      "新增用户",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:user:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改用户",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("manager:user:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{
									{
										App:        "SystemPlatform",
										Title:      "获取用户角色列表",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/manager/v1/user/roles"),
										Method:     proto.String("GET"),
										Path:       nil,
										Permission: proto.String("manager:user:update"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "获取用户部门列表",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/manager/v1/user/jobs"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("manager:user:update"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
								},
							},
							{
								App:        "SystemPlatform",
								Title:      "删除用户",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("manager:user:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "启用/禁用用户",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        nil,
								Method:     nil,
								Path:       nil,
								Permission: proto.String("manager:user:status"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{{
									App:        "SystemPlatform",
									Title:      "启用用户",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/manager/v1/user/enable"),
									Method:     proto.String("POST"),
									Path:       nil,
									Permission: proto.String("manager:user:status:enable"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
									{
										App:        "SystemPlatform",
										Title:      "禁用用户",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/manager/v1/user/disable"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("manager:user:status:disable"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
								},
							},
							{
								App:        "SystemPlatform",
								Title:      "重置账号密码",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/manager/v1/user/password/reset"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("manager:user:reset:password"),
								Component:  proto.String(""),
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
				},
			},
			{
				App:        "SystemPlatform",
				Title:      "配置中心",
				Type:       consts.MenuPage,
				Keyword:    proto.String("SystemPlatformConfigure"),
				Icon:       proto.String("code-block"),
				Api:        nil,
				Method:     nil,
				Path:       proto.String("/configure"),
				Permission: nil,
				Component:  nil,
				Redirect:   nil,
				Weight:     proto.Uint32(0),
				IsHidden:   nil,
				IsCache:    nil,
				IsHome:     nil,
				IsAffix:    nil,
				Children: []*model.Menu{
					{
						App:        "SystemPlatform",
						Title:      "环境管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ConfigureEnv"),
						Icon:       proto.String("common"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/configure/env"),
						Permission: nil,
						Component:  proto.String("configure/env/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查看环境",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environments"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("configure:environment:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增环境",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environment"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("configure:environment:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改环境",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environment"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:environment:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除环境",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environment"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("configure:environment:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "查看环境Token",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environment/token"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("configure:environment:token:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "重置环境token",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/environment/token"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:environment:token:reset"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "服务管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ConfigureServer"),
						Icon:       proto.String("apps"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/configure/server"),
						Permission: nil,
						Component:  proto.String("configure/server/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查询服务",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/servers"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("configure:server:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增服务",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/server"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("configure:server:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改服务",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/server"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:server:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除服务",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/server"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("configure:server:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "资源变量",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ConfigureResource"),
						Icon:       proto.String("unordered-list"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/configure/resource"),
						Permission: nil,
						Component:  proto.String("configure/resource/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查看资源",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/resources"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("configure:resource:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增资源",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/resource"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("configure:resource:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改资源",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/resource"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:resource:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除资源",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/resource"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("configure:resource:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "资源变量值配置",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        nil,
								Method:     nil,
								Path:       nil,
								Permission: proto.String("configure:resource:value"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "业务变量",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ConfigureBusiness"),
						Icon:       proto.String("code"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/configure/business"),
						Permission: nil,
						Component:  proto.String("configure/business/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "查看业务变量",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/business"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("configure:business:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "新增业务变量",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/business"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("configure:business:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "修改业务变量",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/business"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:business:update"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "删除业务变量",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/business"),
								Method:     proto.String("DELETE"),
								Path:       nil,
								Permission: proto.String("configure:business:delete"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "配置业务变量值",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/business/value"),
								Method:     proto.String("PUT"),
								Path:       nil,
								Permission: proto.String("configure:business:value"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
						},
					},
					{
						App:        "SystemPlatform",
						Title:      "配置模板",
						Type:       consts.MenuPage,
						Keyword:    proto.String("ConfgureTemplate"),
						Icon:       proto.String("file"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/configure/template"),
						Permission: nil,
						Component:  proto.String("configure/template/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   nil,
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{
							{
								App:        "SystemPlatform",
								Title:      "配置预览",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        nil,
								Method:     nil,
								Path:       nil,
								Permission: proto.String("configure:template:preview"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{{
									App:        "SystemPlatform",
									Title:      "测试环境",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/configure/v1/template/preview/TEST"),
									Method:     proto.String("POST"),
									Path:       nil,
									Permission: proto.String("configure:template:preview:TEST"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
									{
										App:        "SystemPlatform",
										Title:      "预发布环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/template/preview/PRE"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("configure:template:preview:PRE"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "回归测试环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/template/preview/BETA"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("configure:template:preview:BETA"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "生产环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/template/preview/PROD"),
										Method:     proto.String("POST"),
										Path:       nil,
										Permission: proto.String("configure:template:preview:PROD"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
								},
							},
							{
								App:        "SystemPlatform",
								Title:      "提交模板",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/configure/v1/template"),
								Method:     proto.String("POST"),
								Path:       nil,
								Permission: proto.String("configure:template:add"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
							{
								App:        "SystemPlatform",
								Title:      "同步配置",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        nil,
								Method:     nil,
								Path:       nil,
								Permission: proto.String("configure:configure:sync"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{{
									App:        "SystemPlatform",
									Title:      "测试环境",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/configure/v1/configure/TEST"),
									Method:     proto.String("PUT"),
									Path:       nil,
									Permission: proto.String("configure:configure:sync:TEST"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
									{
										App:        "SystemPlatform",
										Title:      "预发布环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/configure/PRE"),
										Method:     proto.String("PUT"),
										Path:       nil,
										Permission: proto.String("configure:configure:sync:PRE"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "回归测试环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/configure/BETA"),
										Method:     proto.String("PUT"),
										Path:       nil,
										Permission: proto.String("configure:configure:sync:BETA"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "生产环境",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/configure/v1/configure/PROD"),
										Method:     proto.String("PUT"),
										Path:       nil,
										Permission: proto.String("configure:configure:sync:PROD"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
								},
							},
						},
					},
				},
			},
			{
				App:        "SystemPlatform",
				Title:      "资源中心",
				Type:       consts.MenuPage,
				Keyword:    proto.String("SystemPlatformResource"),
				Icon:       proto.String("file"),
				Api:        nil,
				Method:     nil,
				Path:       proto.String("/resource"),
				Permission: nil,
				Component:  nil,
				Redirect:   nil,
				Weight:     proto.Uint32(0),
				IsHidden:   nil,
				IsCache:    nil,
				IsHome:     nil,
				IsAffix:    nil,
				Children: []*model.Menu{
					{
						App:        "SystemPlatform",
						Title:      "文件管理",
						Type:       consts.MenuPage,
						Keyword:    proto.String("File"),
						Icon:       proto.String("file"),
						Api:        nil,
						Method:     nil,
						Path:       proto.String("/resource/file"),
						Permission: nil,
						Component:  proto.String("resource/file/index"),
						Redirect:   nil,
						Weight:     proto.Uint32(0),
						IsHidden:   proto.Bool(false),
						IsCache:    proto.Bool(true),
						IsHome:     nil,
						IsAffix:    proto.Bool(true),
						Children: []*model.Menu{{
							App:        "SystemPlatform",
							Title:      "目录管理",
							Type:       consts.MenuGroup,
							Keyword:    nil,
							Icon:       nil,
							Api:        nil,
							Method:     nil,
							Path:       nil,
							Permission: proto.String("resource:directory:group"),
							Component:  nil,
							Redirect:   nil,
							Weight:     proto.Uint32(0),
							IsHidden:   nil,
							IsCache:    nil,
							IsHome:     nil,
							IsAffix:    nil,
							Children: []*model.Menu{{
								App:        "SystemPlatform",
								Title:      "查看目录",
								Type:       consts.MenuApi,
								Keyword:    nil,
								Icon:       nil,
								Api:        proto.String("/resource/v1/directory"),
								Method:     proto.String("GET"),
								Path:       nil,
								Permission: proto.String("resource:directory:query"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children:   nil,
							},
								{
									App:        "SystemPlatform",
									Title:      "新增目录",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/resource/v1/directory"),
									Method:     proto.String("POST"),
									Path:       nil,
									Permission: proto.String("resource:directory:add"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
								{
									App:        "SystemPlatform",
									Title:      "修改目录",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/resource/v1/directory"),
									Method:     proto.String("PUT"),
									Path:       nil,
									Permission: proto.String("resource:directory:update"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
								{
									App:        "SystemPlatform",
									Title:      "删除目录",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/resource/v1/directory"),
									Method:     proto.String("DELETE"),
									Path:       nil,
									Permission: proto.String("resource:directory:delete"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
							},
						},
							{
								App:        "SystemPlatform",
								Title:      "文件管理",
								Type:       consts.MenuGroup,
								Keyword:    nil,
								Icon:       nil,
								Api:        nil,
								Method:     nil,
								Path:       nil,
								Permission: proto.String("resource:file:group"),
								Component:  nil,
								Redirect:   nil,
								Weight:     proto.Uint32(0),
								IsHidden:   nil,
								IsCache:    nil,
								IsHome:     nil,
								IsAffix:    nil,
								Children: []*model.Menu{{
									App:        "SystemPlatform",
									Title:      "查看文件",
									Type:       consts.MenuApi,
									Keyword:    nil,
									Icon:       nil,
									Api:        proto.String("/resource/v1/files"),
									Method:     proto.String("GET"),
									Path:       nil,
									Permission: proto.String("resource:file:query"),
									Component:  nil,
									Redirect:   nil,
									Weight:     proto.Uint32(0),
									IsHidden:   nil,
									IsCache:    nil,
									IsHome:     nil,
									IsAffix:    nil,
									Children:   nil,
								},
									{
										App:        "SystemPlatform",
										Title:      "修改文件",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/resource/v1/file"),
										Method:     proto.String("PUT"),
										Path:       nil,
										Permission: proto.String("resource:file:upload"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "删除文件",
										Type:       consts.MenuApi,
										Keyword:    nil,
										Icon:       nil,
										Api:        proto.String("/resource/v1/file"),
										Method:     proto.String("DELETE"),
										Path:       nil,
										Permission: proto.String("resource:file:delete"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children:   nil,
									},
									{
										App:        "SystemPlatform",
										Title:      "上传文件",
										Type:       consts.MenuGroup,
										Keyword:    nil,
										Icon:       nil,
										Api:        nil,
										Method:     nil,
										Path:       nil,
										Permission: proto.String("resource:file:upload:group"),
										Component:  nil,
										Redirect:   nil,
										Weight:     proto.Uint32(0),
										IsHidden:   nil,
										IsCache:    nil,
										IsHome:     nil,
										IsAffix:    nil,
										Children: []*model.Menu{{
											App:        "SystemPlatform",
											Title:      "分块上传文件",
											Type:       consts.MenuApi,
											Keyword:    nil,
											Icon:       nil,
											Api:        proto.String("/resource/v1/upload"),
											Method:     proto.String("POST"),
											Path:       nil,
											Permission: proto.String("resource:file:upload"),
											Component:  nil,
											Redirect:   nil,
											Weight:     proto.Uint32(0),
											IsHidden:   nil,
											IsCache:    nil,
											IsHome:     nil,
											IsAffix:    nil,
											Children:   nil,
										},
											{
												App:        "SystemPlatform",
												Title:      "预上传文件",
												Type:       consts.MenuApi,
												Keyword:    nil,
												Icon:       nil,
												Api:        proto.String("/resource/v1/upload/prepare"),
												Method:     proto.String("POST"),
												Path:       nil,
												Permission: proto.String("resource:file:upload"),
												Component:  nil,
												Redirect:   nil,
												Weight:     proto.Uint32(0),
												IsHidden:   nil,
												IsCache:    nil,
												IsHome:     nil,
												IsAffix:    nil,
												Children:   nil,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
}
