server:
  http:
    addr: 0.0.0.0:7002
    timeout: 10s
    marshal:
      emitUnpopulated: false
      useProtoNames: true
  grpc:
    addr: 0.0.0.0:8002
    timeout: 10s
log:
  level: 0 #日志输出等级
  output:
    - stdout # stdout:控制台输出，k8s日志收集
    - file # file:输出到文件
  file: #output存在file时此配置才可生效
    name: ./tmp/runtime/output.log #日志存放地址
    maxSize: 1 #日志文件最大容量,单位m
    maxBackup: 5 #日志文件最多保存个数
    maxAge: 1 #保留就文件的最大天数,单位天
    compress: false #是否进行压缩归档
database:
  system: #数据库实例名称,如有多个数据库可新增
    enable: true #是否启用数据库
    drive: mysql #数据库类型
    dsn: root:root@tcp(127.0.0.1:3306)/basic_platform?charset=utf8mb4&parseTime=True&loc=Local #连接dsn
    maxLifetime: 2h #最大生存时间
    maxOpenConn: 10 #最大连接数量
    maxIdleConn: 10 #最大空闲数量
    logLevel: 4 #日志等级
    slowThreshold: 2s #慢sql阈值
redis:
  cache: #redis实例名称,如有多个redis可新增
    enable: true #是否启用redis
    host: 127.0.0.1:6379 #redis地址
    username:  #连接账号
    password:  #连接密码
captcha:
  login:  #验证码名称
    type: image #验证码类型 目前支持image/email
    length: 6 #验证码长度
    expire: 180s #过期时间
    redis: cache #redis名称
    height: 80 #图片高度,仅image有效
    width: 240 #图片宽度,仅image有效
    skew: 0.7 #验证数字倾斜程度,仅image有效
    dotCount: 80 #干扰像素点数量,仅image有效
  changePassword:  #验证码名称
    type: email #验证码类型
    length: 6 #验证码长度
    expire: 180s #过期时间
    redis: cache #redis名称
    template: captcha #邮箱模板名称,仅email有效
loader:
  login: static/cert/login.pem

email: # 邮件发送相关配置
  template: #邮件模板
    captcha:  #邮件模板名称
      subject: 验证码发送通知 #邮件模板主题
      path: static/template/email/default.html #邮件模板路径
      from: xxx@qq.com
      type: "text/html" #文本内容格式
  user: 860808187@qq.com #发送者
  host: smtp.qq.com:25 #发送host
  password: ersukmsstobebdef # 发送host密码
jwt:
  redis: cache
  secret: limeschool #密钥
  expire: 2h #过期时间
  renewal: 1s #续期时间
  prefix: /basic #url前缀
  whitelist: #忽略token校验以及鉴权的白名单 http 方法名:path  grpc GRPC:operation
    POST:/basic/v1/login/captcha: true # 验证码
    POST:/basic/v1/login: true  # 登录
    POST:/basic/v1/token/refresh: true # 刷新
authentication:
  db: system #db名称
  redis: cache #redis名称
  roleKey: role_keyword #jwt中存储角色的关键字的下标
  skipRole: ["super_admin"] #跳过检查的角色
  whitelist: # 跳过权限检查的接口

    POST:/basic/v1/login: true  # 登录
    POST:/basic/v1/login/captcha: true # 验证码
    POST:/basic/v1/logout: true # 退出
    POST:/basic/v1/token/refresh: true # 刷新
    GET:/basic/v1/user/current: true # 个人信息
    GET:/basic/v1/role/menu/tree: true #获取角色菜单
    #v1:Greeter/SayHello: true #http和grpc通用 包名.服务名.函数名 具体可在pb里面查看
ratelimit: true #是否开启限流

#以下存放业务配置
business:
#  defaultUserAvatar: logo.png
  defaultUserPassword: 12345678

