---
server:
  http:
    addr: 127.0.0.1:7001
    timeout: 10s
    marshal:
      emitUnpopulated: true
      useProtoNames: true
  grpc:
    addr: 127.0.0.1:8001
    timeout: 10s
log:
  level: 0
  output:
    - stdout
    - file
  file:
    name: "./tmp/runtime/output.log"
    maxSize: 1
    maxBackup: 5
    maxAge: 1
    compress: false
database:
  system: #数据库实例名称,如有多个数据库可新增
    enable: true #是否启用数据库
    drive: mysql #数据库类型
    autoCreate: true #是否自动创建数据库
    connect:
      username: root
      password: root
      host: 127.0.0.1
      port: 3306
      dbName: manager
      option: ?charset=utf8mb4&parseTime=True&loc=Local
    config:
      transformError:
        enable: true
      maxLifetime: 2h #最大生存时间
      maxOpenConn: 10 #最大连接数量
      maxIdleConn: 10 #最大空闲数量
      logLevel: 4 #日志等级
      slowThreshold: 2s #慢sql阈值
redis:
  cache:
    enable: true
    host: 127.0.0.1:6379
    username: ''
    password: ''
captcha:
  login:
    type: image
    length: 6
    expire: 180s
    redis: cache
    height: 80
    width: 240
    skew: 0.7
    dotCount: 80
  changePassword:
    type: email
    length: 6
    expire: 180s
    redis: cache
    template: captcha
loader:
  login: static/cert/login.pem
email:
  template:
    captcha:
      subject: 验证码发送通知
      path: static/template/email/default.html
      type: text/html
  user: 860808187@qq.com
  name: 青岑云
  host: smtp.qq.com
  port: 25
  password: fyudafdzqmhwbfbd
jwt:
  redis: cache
  secret: limeschool
  expire: 2h
  renewal: 20s
  whitelist:
    GET:/manager/v1/setting: true
    POST:/manager/v1/login/captcha: true
    POST:/manager/v1/login: true
    POST:/manager/v1/token/refresh: true
authentication:
  db: system
  redis: cache
  roleKey: role_keyword
  skipRole:
    - superAdmin
  whitelist: {}
business:
  defaultUserPassword: '12345678'
  setting:
    name: admin-platefrom
    title: easy-admin 后台管理系统
    desc: 开放协作，拥抱未来，插件化编程实现
    copyright: Copyright © 2023 lime.qlime.cn. All rights reserved.
    logo: http://p3-armor.byteimg.com/tos-cn-i-49unhts6dw/dfdba5317c0c20ce20e64fac803d52bc.svg~tplv-49unhts6dw-image.image
